name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish -c Release

      # Clean target directory before deployment
      - name: Clean target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: 22
          script: |
            rm -rf /mnt/deployments/TheSandooq/*
            mkdir -p /mnt/deployments/TheSandooq/

      # Deploy via SCP using the default publish location
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: 22
          source: "/home/runner/work/TheSandooq/TheSandooq/TheSandooq/bin/Release/net8.0/publish/"   # Adjust if your target framework or project structure differs
          target: "/mnt/deployments/TheSandooq/"

      # Run deployment commands on your VPS using SSH
      - name: Run SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: 22
          script: |
            sudo systemctl restart thesandooq.service
